[template]
prefix = "tomcat"
keys = [
  "user",
  "password",
  "Xmx",
  "Xms"
]

src = "tomcat-users.xml.tmpl"
dest = "/usr/local/tomcat/conf/tomcat-users.xml"

reload_cmd = "/usr/local/tomcat/bin/catalina.sh stop -force && /usr/local/tomcat/bin/catalina_start.sh"
